Remove keycloak/egi login as package is not ts lint correct until 2.0.5 is released
Lint error is corrected in main, but missing release.

Following error:

node_modules/remix-keycloak/build/index.d.ts:39:22 - error TS2415: Class 'KeycloakStrategy<User>' incorrectly extends base class 'OAuth2Strategy<User, KeycloakProfile, KeycloakExtraParams>'.
  Property 'scope' is private in type 'KeycloakStrategy<User>' but not in type 'OAuth2Strategy<User, KeycloakProfile, KeycloakExtraParams>'.

39 export declare class KeycloakStrategy<User> extends OAuth2Strategy<User, KeycloakProfile, KeycloakExtraParams> {